name: corridle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_maps_flutter: ^2.2.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.0 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  googleapis: ^3.0.0
  fl_chart: ^0.64.0
  googleapis_auth: ^1.4.1
  image_picker: ^1.1.2  
  google_fonts: ^4.0.4
  animate_do: ^3.0.2 # Add animation package
  carousel_slider: ^4.2.1
  firebase_database: ^11.3.0
  permission_handler: ^11.0.1
  shimmer: ^2.0.0
  path: ^1.9.1


    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
